"""HTML email composition and sending."""

import logging
import os
import smtplib
from datetime import datetime
from email.mime.image import MIMEImage
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import List, Optional

from src.chart import chart_to_base64

logger = logging.getLogger(__name__)

SMTP_SERVER = os.environ.get("SMTP_SERVER", "smtp.gmail.com")
SMTP_PORT = int(os.environ.get("SMTP_PORT", "587"))
SMTP_USER = os.environ.get("SMTP_USER", "")
SMTP_PASSWORD = os.environ.get("SMTP_PASSWORD", "")
NOTIFY_EMAIL = os.environ.get("NOTIFY_EMAIL", "")


def _get_recipients() -> List[str]:
    if not NOTIFY_EMAIL:
        return []
    return [addr.strip() for addr in NOTIFY_EMAIL.split(",") if addr.strip()]


def _format_volume(value: float) -> str:
    return f"${value:,.2f}"


def _format_ratio(value: float) -> str:
    return f"{value:.6f}"


def _compute_stats(df, today_date: str, today_ratio: float) -> dict:
    """Compute summary statistics for the email."""
    stats = {
        "ratio": _format_ratio(today_ratio),
        "ma7": "N/A",
        "ma30": "N/A",
        "vs_yesterday": "N/A",
        "status": "Normal",
        "status_bg": "transparent",
        "alert_flag": "",
    }

    if not df.empty and "ratio" in df.columns:
        ratios = df["ratio"].astype(float)
        # 7-day avg
        if len(ratios) >= 7:
            stats["ma7"] = _format_ratio(ratios.tail(7).mean())
        else:
            stats["ma7"] = f"N/A ({len(ratios)} days of data)"

        # 30-day avg
        if len(ratios) >= 30:
            stats["ma30"] = _format_ratio(ratios.tail(30).mean())
        else:
            stats["ma30"] = f"N/A ({len(ratios)} days of data)"

        # vs yesterday
        prev = df[df["date"] < today_date]
        if not prev.empty:
            last_ratio = float(prev.iloc[-1]["ratio"])
            change = ((today_ratio - last_ratio) / last_ratio) * 100
            arrow = "▲" if change >= 0 else "▼"
            stats["vs_yesterday"] = f"{arrow} {change:+.2f}%"

        # ATH / ATL
        ath = ratios.max()
        atl = ratios.min()
        if today_ratio >= ath:
            stats["status"] = "ALL-TIME HIGH"
            stats["status_bg"] = "#ffcccc"
            stats["alert_flag"] = "ATH!"
        elif today_ratio <= atl:
            stats["status"] = "ALL-TIME LOW"
            stats["status_bg"] = "#ccccff"
            stats["alert_flag"] = "ATL!"

    return stats


def send_report(date: str, hl_volume: float, bn_volume: float, today_ratio: float, chart_path: str, df) -> None:
    """Send the daily HTML report email."""
    recipients = _get_recipients()
    if not recipients or not SMTP_USER or not SMTP_PASSWORD:
        logger.warning("Email credentials not configured; skipping report email")
        return

    stats = _compute_stats(df, date, today_ratio)
    subject = f"[Perp Tracker] {date} | Ratio: {stats['ratio']} {stats['alert_flag']}"

    img_b64 = chart_to_base64(chart_path)
    img_tag = f'<img src="data:image/png;base64,{img_b64}" alt="Ratio Chart" style="max-width:100%;"/>' if img_b64 else ""

    html = f"""\
<html>
<body style="font-family: Arial, sans-serif; color: #333;">
    <h2>Perp Volume Ratio Daily Report</h2>
    <p><strong>Date:</strong> {date}</p>
    <table border="1" cellpadding="8" cellspacing="0" style="border-collapse: collapse; width: 100%; max-width: 600px;">
        <tr><td>Hyperliquid 24h Volume</td><td>{_format_volume(hl_volume)}</td></tr>
        <tr><td>Binance 24h Volume</td><td>{_format_volume(bn_volume)}</td></tr>
        <tr><td>Ratio (HL/BN)</td><td>{stats['ratio']}</td></tr>
        <tr><td>7-Day Avg Ratio</td><td>{stats['ma7']}</td></tr>
        <tr><td>30-Day Avg Ratio</td><td>{stats['ma30']}</td></tr>
        <tr><td>vs Yesterday</td><td>{stats['vs_yesterday']}</td></tr>
        <tr style="background-color: {stats['status_bg']};">
            <td><strong>Status</strong></td>
            <td><strong>{stats['status']}</strong></td>
        </tr>
    </table>
    <br>
    {img_tag}
    <br>
    <p style="font-size: 12px; color: #666;">Auto-generated by perp-volume-tracker</p>
</body>
</html>
"""

    msg = MIMEMultipart("related")
    msg["Subject"] = subject
    msg["From"] = SMTP_USER
    msg["To"] = ", ".join(recipients)
    msg.attach(MIMEText(html, "html"))

    try:
        with smtplib.SMTP(SMTP_SERVER, SMTP_PORT) as server:
            server.starttls()
            server.login(SMTP_USER, SMTP_PASSWORD)
            server.sendmail(SMTP_USER, recipients, msg.as_string())
        logger.info("Report email sent to %s", recipients)
    except Exception as exc:
        logger.error("Failed to send report email: %s", exc)


def send_alert(date: str, hl_error: Optional[str], bn_error: Optional[str]) -> None:
    """Send a plain-text alert email when API calls fail."""
    recipients = _get_recipients()
    if not recipients or not SMTP_USER or not SMTP_PASSWORD:
        logger.warning("Email credentials not configured; skipping alert email")
        return

    lines = [f"Data Collection Error — {date}", ""]
    if hl_error:
        lines.append(f"Hyperliquid API failed: {hl_error}")
    if bn_error:
        lines.append(f"Binance API failed: {bn_error}")
    lines.append("")
    lines.append("No data was written to the CSV for this run.")

    body = "\n".join(lines)
    subject = f"[Perp Tracker] Warning: Data Collection Error — {date}"

    msg = MIMEText(body)
    msg["Subject"] = subject
    msg["From"] = SMTP_USER
    msg["To"] = ", ".join(recipients)

    try:
        with smtplib.SMTP(SMTP_SERVER, SMTP_PORT) as server:
            server.starttls()
            server.login(SMTP_USER, SMTP_PASSWORD)
            server.sendmail(SMTP_USER, recipients, msg.as_string())
        logger.info("Alert email sent to %s", recipients)
    except Exception as exc:
        logger.error("Failed to send alert email: %s", exc)
